### ISSUE TITLE
Invalid field name when building

### ISSUE THREAD

**Issue by wrgtri** [PX4/px4_ros_com#60]
When attempting to run ./build_ros2_workspace.bash, I get the error below. Is what's causing this error that "fault_status_bad_Airspeed" should be "fault_status_bad_airspeed"?
```
pi4@pi4-desktop:~/px4_ros_com_ros2/src/px4_ros_com/scripts$ ./build_ros2_workspace.bash 
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
Cloning into 'ros1_bridge'...
remote: Enumerating objects: 47, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 1341 (delta 23), reused 23 (delta 10), pack-reused 1294
Receiving objects: 100% (1341/1341), 1.51 MiB | 4.50 MiB/s, done.
Resolving deltas: 100% (821/821), done.
Starting >>> px4_msgs
--- stderr: px4_msgs                           
CMake Error at /opt/ros/foxy/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
  execute_process(/usr/bin/python3 -m rosidl_adapter --package-name px4_msgs
  --arguments-file
  /home/pi4/px4_ros_com_ros2/build/px4_msgs/rosidl_adapter__arguments__px4_msgs.json
  --output-dir
  /home/pi4/px4_ros_com_ros2/build/px4_msgs/rosidl_adapter/px4_msgs
  --output-file
  /home/pi4/px4_ros_com_ros2/build/px4_msgs/rosidl_adapter/px4_msgs.idls)
  returned error code 1:

  Error processing 'bool fault_status_bad_Airspeed' of
  'px4_msgs/EstimatorStatusFlags': ''fault_status_bad_Airspeed' is an invalid
  field name.  It should have the pattern
  '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$''

  Traceback (most recent call last):

    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
      msg = parse_message_string(package_name, input_file.stem, content)
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 512, in parse_message_string
      fields.append(Field(
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 353, in __init__
      raise NameError(

  NameError: 'fault_status_bad_Airspeed' is an invalid field name.  It should
  have the pattern '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$'

Call Stack (most recent call first):
  /opt/ros/foxy/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:44 (rosidl_generate_interfaces)


---
Failed   <<< px4_msgs [11.8s, exited with code 1]

Summary: 0 packages finished [12.6s]
  1 package failed: px4_msgs
  1 package had stderr output: px4_msgs
  1 package not processed

```

**Comment by wrgtri** [comment]
px4_msgs/msg/EstimatorStatusFlags.msg contains fault_status_bad_Airspeed and reject_Airspeed, both of which need to be changed to all lowercase in order for the package to be built successfully.
